version: 2.1
jobs:
  pr_check:
    docker:
      - image: node:11.10.1

    steps:
      - checkout

      - run: npm install
      # - run: apt-get install mocha
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: "Build"
          command: node ciserver.js

      - run:
          name: "Test"
          command: |
            npm run test
            echo 'Done'
  build:
    docker:
      - image: node:11.10.1

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      # run tests!
      - run:
          name: "Test"
          command: node ciserver.js
          # background: true
      - run:
          name: "Test"
          command: npm run test

      - run:
          name: "Zip"
          command: |
            apt-get update
            apt-get install zip
      - run:
          command: zip -r artifacts.zip . -x '*aws/*' '*node_modules'
      - run:
          name: "Upload to S3"
          command: npm run upload
  deploy:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
          aws-access-key-id: AWS_KEY
          aws-secret-access-key: AWS_SECRET
          aws-region: AWS_REGION
      - run:
          name: CodeDeploy
          command: aws deploy create-deployment --application-name csye6225-webapp --s3-location bucket=$CDS3BUCKET,key=artifacts.zip,bundleType=zip --deployment-group-name csye6225-webapp-deployment

orbs:
  aws-cli: circleci/aws-cli@0.1.22

workflows:
  version: 2
  pr_check_workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
  # build_deploy:
  #   jobs:
  #     - build:
  #         filters:
  #           branches:
  #             only: master
