version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest # The primary container where steps are run
      # - image: circleci/mysql:8.0.4
      #   environment:
      #     MYSQL_ROOT_PASSWORD: Shakti123
      #     MYSQL_DATABASE: test_db
      #     MYSQL_USER: root

          

    steps:
      - checkout
      
      - run: sudo apt-get install mysql-server
      - run: sudo service mysql start
      - run: sudo mysql -u root 

workflows:
  version: 2
  build-deploy:
    jobs:
      - build