version: 2
jobs:
  build:
    docker:
      - image: circleci/mysql:5.7.29  # The primary container where steps are run
      - image: circleci/node:latest
        environment:
          
          
          MYSQL_USER: root

          

    steps:
      - checkout
      - run: apt-get install mysql-server
      - run: service mysql start
      - run: 
          command: |
            
            echo "SELECT OK" | mysql --user=root --host=localhost --execute='CREATE DATABASE test' 

      - run:
          name: Update npm
          command: 'npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: node server.js
            

workflows:
  version: 2
  build-deploy:
    jobs:
      - build