version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:latest
      - image: circleci/mysql:5.7.29
        environment:
          MYSQL_HOST: localhost
          MYSQL_DATABASE: test
          MYSQL_USER: root
          # MYSQL_PASSWORD: passw0rd
    steps:
      - checkout
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1:3006 -u user -ppassw0rd --execute="CREATE database test_db"
            
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: node server.js
  test:
    docker:
      - image: circleci/node:4.8.2-jessie
      
    steps:
      - checkout
      - run: node server.js
          
        # - run:
        #     name: Generate code coverage
        #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
        # - store_artifacts:
        #     path: test-results.xml
        #     prefix: tests
        # - store_artifacts:
        #     path: coverage
        #     prefix: coverage

            
  
  
workflows:
  version: 2
  pr_check_workflow:
    jobs:
      - pr_check
  # build_check_workflow:
  #   jobs:
  #     - build 
      