version: 2
jobs:
  pr_check:
    docker:
      - image: node:11.10.1

    steps:
      - checkout

      - run: npm install
      # - run: apt-get install mocha
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: "Build"
          command: node ciserver.js

      - run:
          name: "Test"
          command: |
            npm run test
            echo 'Done'
  build:
    docker:
      - image: node:11.10.1

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - run:
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - run:
          command: unzip awscliv2.zip

      - run:
          command: ./aws/install
      # run tests!
      - run:
          name: "Build"
          command: node ciserver.js
          # background: true
      - run:
          name: "Test"
          command: npm run test
      - run:
          command: |
            apt-get update
            apt-get install zip

      - run:
          command: zip -r artifacts.zip . -x '*aws/*' '*node_modules'
workflows:
  version: 2
  pr_check_workflow:
    jobs:
      - build
  # build_deploy:
  #   jobs:
  #     - build:
  #         filters:
  #           branches:
  #             only: master
