version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest # The primary container where steps are run
      # - image: circleci/mysql:8.0.4
      #   environment:
      #     MYSQL_ROOT_PASSWORD: Shakti123
      #     MYSQL_DATABASE: test_db
      #     MYSQL_USER: root

          

    steps:
      - checkout
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run: sudo yum install mysql-community-server
      - run: sudo service mysql start
      - run: mysql -u root 

workflows:
  version: 2
  build-deploy:
    jobs:
      - build